<template>
    <div class="terms-container">
        <div class="inner-container">
            <p class="main-title flex-align__center">Terms of Service</p>
            <p class="flex-align__center">Last Updated: August 11, 2021</p>
            <p>Thank you for signing up for Muso.AI.  As a MUSO.AI customer, you must abide by these <span class="text-bold">“Terms,”</span> including the copyright and corporate espionage provisions hereof.  Welcome to Muso.AI.
            </p>
            <p>MUSO.AI (together with our subsidiaries and other affiliates) is hereinafter referred to as <span class="text-bold">“MUSO.AI”, “we”, “us”</span> and <span class="text-bold">“our.”</span> 
            </p>
            <p>MUSO.AI provides a variety of services to songwriters, musicians and vendors in the music industry that are collectively referenced herein as the <span class="text-bold">“MUSO.AI Services.”</span></p>
            <p>The MUSO.AI Services are ordered online and will appear in your MUSO.AI account. Your authorization to use the MUSO.AI Services is conditioned on your acceptance of and compliance with these Terms.
            </p>
            <p>The MUSO.AI Services are provided through this website which is operated by proprietary software owned by MUSO.AI that shall hereinafter be referred to as the <span class="text-bold">“MUSO.AI. Platform.”</span>  Unless otherwise specified, the term MUSO.AI Services shall include the MUSO.AI Platform throughout these Terms. 
            </p>
            <p class="text-bold">PLEASE REVIEW THESE TERMS CAREFULLY. BY ACCEPTING THEM AND USING THE MUSO.AI SERVICES, YOU AGREE TO THESE TERMS WHICH CREATES A BINDING AGREEMENT BETWEEN MUSO.AI AND YOU. 
            </p>
            <p>Your account registration constitutes an acknowledgement that you can electronically receive, read and understand these Terms, and that you consent to conducting business with us electronically.
            </p>
            <p class="text-bold">YOU MAY NOT USE THIS SITE TO GATHER COMPETITIVE INTELLIGENCE ABOUT MUSO.AI, SOMETIMES REFERRED TO AS CORPORATE INTELLIGENCE.  COMPETITIVE INTELLIGENCE REFERS TO THE GATHERING, ANALYZING AND USE OF INFORMATION COLLECTED FROM MUSO.AI TO COMPETE AGAINST MUSO.AI IN THE MARKET PLACE.  MUSO.AI HAS SPENT MILLIONS OF DOLLARS IN CREATING AND FINE-TUNING ITS OFFERINGS, AND WILL NOT ALLOW OTHERS TO STEAL ITS INTELLECTUAL PROPERTY AND TRADE SECRETS TO COMPETE AGAINST IT.  IMPROPER USES OF MUSO.AI’S INTELLECTUAL PROPERTY AND TRADE SECRETS WILL BE PROSECUTED TO THE FULLEST EXTENT ALLOWED BY THE LAW. FURTHERMORE, PLEASE BE ADVISED THAT MUSO.AI HAS MONITORS THE USE OF THE MUSO.AI SERVICES. THEREFORE, BE FOREWARNED THAT USE OF THE MUSO.AI SERVICES FOR COMPETITIVE INTELLIGENCE PURPOSES WILL BE KNOWN TO MUSO.AI. </p>
            <p>This Agreement applies to all users of the MUSO.AI Services (collectively, <span class="text-bold">“users”</span>). If you are registering to use the MUSO.AI Services as an individual, references to <span class="text-bold">“you”</span> are to you. If you are registering to use the MUSO.AI Services on behalf of an entity or organization, references to <span class="text-bold">“you”</span> include you personally and such entity or organization and its employees and contractors.  In such instance, you represent that you have the authority to bind that entity or organization to these Terms.
            </p>
            <p>Furthermore, MUSO.AI and you may be referred to individually as a <span class="text-bold">“party”</span> or collectively as the <span class="text-bold">“parties.”</span> 
            </p>
            <p class="text-bold">THESE TERMS CONTAIN AN AGREEMENT TO ARBITRATE WHICH REQUIRES, AMONG OTHER THINGS, THAT DISPUTES RELATING TO THESE TERMS, YOUR ACCOUNT OR THE MUSO.AI SERVICES BE RESOLVED BY BINDING ARBITRATION ON AN INDIVIDUAL BASIS ONLY.
            </p>
            <p class="text-bold">1. MUSO.AI Services.</p>
            <p>1.1 <span class="text-underline">MUSO.AI Services.</span></p>
            <p>(a) <span class="text-italic">Provision of MUSO.AI Services.</span> MUSO.AI makes the MUSO.AI Services available to you under these Terms and any supplemental policies or terms made applicable from time-to-time (collectively, <span class="text-bold">"Supplemental Terms"</span>), all of which are incorporated into these Terms. In the event of a conflict between the provisions of these Terms and any Supplemental Terms, the Supplemental Terms will control.
            </p>
            <p>(b) <span class="text-italic">MUSO.AI Services.</span> The MUSO.AI Services principally include the following: (i) a library of verified music credits; (ii) data regarding music ownership, artists and credits; (iii) an API that allows users to access the MUSO.AI library and data; (iv) other features developed by MUSO.AI from time to time; and (v) use of the MUSO.AI Platform.</p>
            <p>(c)  <span class="text-italic">Content.</span>  The library of verified music credits and data contained in the MUSO.AI Services are hereinafter referred to as the <span class="text-bold">“MUSO.AI Content.”</span> MUSO.AI hereby grants you a limited, revocable, non-sublicensable license to use, reproduce and copy the MUSO.AI Content solely for your use, subject to your compliance with these Terms. You may not resell any of the MUSO.AI Services (including the MUSO.AI Content) to any third party.  Any data (i.e., regarding music industry credits, for example) that you provide to MUSO.AI may be shared with other music industry companies to ensure that it is uniformly maintained throughout the music industry ecosystem. 
            </p>
            <p>1.2 <span class="text-underline">Additional Services.</span> MUSO.AI may make additional MUSO.AI Services available to you from time-to-time that are subject to additional terms. Furthermore, if you are transferred to an external site while using the MUSO.AI Services, your use of such third-party site is subject to the terms and conditions of its owner.    
            </p>
            <p>1.3 <span class="text-underline">Disclosures.</span>  MUSO.AI is not responsible for the accuracy of the MUSO.AI Content  contained within the MUSO.AI Services, as it is obtained from users like you (who contribute it, much like Wikipedia) and third-party services.  Any MUSO.AI Content made available to you from the MUSO.AI Services is intended for your general use only.  MUSO.AI cannot guarantee its accuracy or the ownership of music credits, nor can it prevent the assertion of adverse claims to credits for music, songs or lyrics. The MUSO.AI Services are not a legal or professional conclusion as to ownership of music, songs or lyrics. You are responsible for any actions that you take based on information obtained from MUSO.AI.  Please obtain professional advice from a lawyer or music industry professional if disputes arise regarding ownership of credits related to music, songs or lyrics contained within the MUSO.AI Services.</p>
            <p>1.4 <span class="text-underline">Eligibility and Jurisdiction.</span>The MUSO.AI Services are available to persons in jurisdictions in which they may be legally sold. Nothing in the MUSO.AI Services shall be considered a solicitation to buy or an offer to sell anything in a jurisdiction in which such offer, solicitation, purchase or sale is unlawful. The technology and software used by MUSO.AI to provide the MUSO.AI Services is subject to United States export controls. No such technology and software may be exported or re-exported in violation of U.S. export laws. 
            </p>
            <p>Furthermore, using the MUSO.AI Services is at your sole risk. The MUSO.AI Services are designed primarily for use within the United States, and you are responsible for their use outside of the United States. Recognizing the global nature of the Internet, you agree to comply with all local rules and laws regarding your use of the MUSO.AI Services.  For that reason, MUSO.AI disclaims any liability regarding use of the MUSO.AI Services that differs from that permitted hereunder.</p>
            <p>1.5 <span class="text-underline">User Limitations.</span> The MUSO.AI Services may only be accessed by users that are at least 13 years of age and are not otherwise barred from using them under applicable law. You are responsible for ensuring that you and any user that you allow to access the MUSO.AI Services are authorized to do so by law, and that such use complies with all wage and hour, employment and any other laws and regulations.
            </p>
            <p>1.6  <span class="text-underline">No Follow-On Sales.</span>  It is a violation of these Terms to sell products or services to other users of the MUSO.AI Services, such as, for example, artists or writers whose names appear in the MUSO.AI Content. Therefore, you agree to use the MUSO.AI Services solely for their intended use (i.e., as described herein), and not to market or sell any products or services to others.</p>
            <p>1.7 <span class="text-underline">Mobile Services.</span> The MUSO.AI Services are available through a mobile device, including (i) the ability to upload content to the MUSO.AI Services; (ii) the ability to browse the MUSO.AI Services and other websites; and (iii) the ability to access certain features (collectively, the <span class="text-bold">“Mobile Services”</span>). If you access the MUSO.AI Services through a mobile device, your wireless carrier’s standard charges, data rates and other fees may apply. In addition, downloading, installing or using certain Mobile Services may be prohibited or restricted by your carrier, and not all Mobile Services work with all carriers or devices. By using the Mobile Services, you agree that we may communicate with you by SMS, MMS, text message or other electronic means to your mobile device, and that information about your usage may be communicated to us. If you change or deactivate your mobile telephone number, promptly update your account information to ensure that your messages are not sent to the person that acquires your old number.
            </p>
            <p class="text-bold">2.   Your Responsibilities.</p>
            <p>2.1 <span class="text-underline">Consent to Electronic Delivery; Electronic Signature.</span></p>
            <p>(a) <span class="text-italic">Electronic Signature.</span>  Your agreement to these Terms electronically is the legal equivalent of agreeing hereto by use of your manual or handwritten signature. 
            </p>
            <p>(b) <span class="text-italic">Electronic Delivery.</span> You agree that MUSO.AI may electronically deliver documents and/or disclosures to you via the email address that you provided to us when you registered. If you are using the MUSO.AI Services on behalf of an entity or organization and/or its employees and contractors, you represent that you have their affirmative consent to receive electronic disclosures for them through the MUSO.AI Services.
            </p>
            <p>(c) <span class="text-italic">Withdrawing Consent.</span> You may withdraw your consent to electronic signatures or electronic disclosures at any time. However, if you do so: (i) MUSO.AI cannot guarantee that you will obtain relevant disclosures or maintain full access to the MUSO.AI Services; (ii) you may be required to obtain paper copies of your documents and notices directly from MUSO.AI or your  employer or contractor (if they have received them for you); and (iii) you may incur additional fees for requesting paper copies from MUSO.AI. You acknowledge that MUSO.AI relies on electronic communications as a core component of its services; accordingly, if you are using the MUSO.AI Services on behalf of a company and/or its employees and contractors, and you withdraw electronic consent, MUSO.AI may be unable to provide the MUSO.AI Services to you and may terminate your use of them in whole or in part.
            </p>
            <p>2.2 <span class="text-underline">Accuracy of Information.</span> The MUSO.AI Services are based on information provided by you and third-party services from which you elect to import information (<span class="text-bold">“User Representations”</span>). You must review all User Representations to ensure that they are accurate and complete. You acknowledge that MUSO.AI is entitled to rely conclusively on all User Representations, and that MUSO.AI does not have an obligation to verify, correct, or otherwise ensure the accuracy or quality of User Representations. You further acknowledge that MUSO.AI bears no responsibility and shall not have liability for errors, omissions, penalties, fines, incorrect coverage or any other losses incurred that result from inaccurate or incomplete User Representations.</p>
            <p>2.3 <span class="text-underline">User Data.</span> With respect to any personal information that you provide to MUSO.AI simply to use the MUSO.AI Services (i.e., such as your name, address, phone number, email address)(collectively, <span class="text-bold">“User Data”</span>), you represent and warrant that you have the necessary rights and permissions to use, make available and send us such User Data (i.e., that may belong to others within an entity or organization) regarding your use of the MUSO.AI Services. 
            </p>
            <p>You agree that MUSO.AI may preserve User Data if required by law or in a good faith belief that its preservation or disclosure is necessary to: (i) comply with legal process, applicable laws or government requests; (ii) enforce these Terms; (iii) respond to claims that any content violates the rights of third parties; or (iv) protect the rights, property, or personal safety of MUSO.AI, its users and the public. You understand that the technical processing and transmission of the MUSO.AI Services, including User Data, may involve transmissions over various networks.
            </p>
            <p>2.4 <span class="text-underline">Account Administration; Authorizations.</span>
            (a)    <span class="text-italic">Accounts.</span> To use the MUSO.AI Services, each user must create an account (an <span class="text-bold">“Account”</span>) by providing their email address (<span class="text-bold">“Account Email”</span>) and a master password (the <span class="text-bold">“Master Password;”</span> collectively, the <span class="text-bold">“Credentials”</span>).  For purposes of clarity, the term Credentials likely includes User Data (as defined above). You and each user are responsible for the security of your or their Account and Credentials. You understand that your Account is solely for your use, and that you will not share your Account or Credentials with anyone. You are fully responsible for all activities on the MUSO.AI Platform associated with your Account. And, if you are an entity or organization, you are fully responsible for all activities of your employees and contractors that use the MUSO.AI Services and in ensuring their compliance herewith.  
            </p>
            <p>(b) <span class="text-italic">Account Administration.</span> If you work with others or are part of an entity or organization, you will designate and authorize one or more individuals with authority to (i) act on your behalf; (ii) provide information on your behalf; and (iii) bind you and/or your business with respect to the MUSO.AI Services (each such individual, an <span class="text-bold">“Account Administrator”</span>). As an Account Administrator, you are solely responsible for all actions taken under an account assigned to you, your employer and all employees and contractors of your employer. Any actions taken under such accounts will be deemed authorized by you, regardless of your knowledge of such actions (the <span class="text-bold">“Authorized Actions”</span>).  Authorized Actions include but are not limited to; (i) actions taken by you, your employer and all employees and contractors of your employer; and (ii) actions that MUSO.AI reasonably believes to have been authorized by you, your employer and all employees and contractors of your employer. </p>
            <p>(c) <span class="text-italic">Account Information.</span> To access or use certain aspects of the MUSO.AI Services, you may need to provide your account information at third party institutions, such as credit card companies or banks, music databases or music companies. Further, MUSO.AI may also require relevant information such as signatures, data, passwords, usernames, PINs and other necessary information, and materials and content from your accounts at other companies (<span class="text-bold">“Account Information”</span>). You retain all right, title and interest in and to your Account Information, and represent and warrant that the Account Information provided is accurate and complete, and may be provided to MUSO.AI without any obligations imposed on MUSO.AI to verify the accuracy or completeness of such Account Information. You are responsible for making sure that MUSO.AI can access such information and that it is accurate. 
            </p>
            <p>(d) <span class="text-italic">Communications and Notifications.</span> You are responsible for reviewing any reports, filings, information, documents or materials (collectively, the <span class="text-bold">“Materials”</span>) made available to you by MUSO.AI for your review, if any, and you must notify MUSO.AI of any inaccuracies in the Materials as soon as possible. You must promptly notify MUSO.AI of any third party notices that you receive that may affect MUSO.AI’s ability to effectively provide the MUSO.AI Services to you (e.g., notices from the Internal Revenue Service, music publishers, music clearinghouses).</p>
            <p>2.5 <span class="text-underline">Third Party Products.</span>
            (a) <span class="text-italic">Independent Services.</span> The MUSO.AI Services are designed to work with many third-party websites, services and applications (<span class="text-bold">“Third Party Products”</span>).  MUSO.AI does not provide any representations, warranties, indemnities, or support with respect to such Third Party Products, unless otherwise agreed in writing. For the interoperation of the selected Third Party Products with the MUSO.AI Services, you may be required to obtain access to such Third Party Products directly from their providers and/or grant MUSO.AI the ability to create, access, delete and/or otherwise modify your account(s) with such Third Party Products. 
            </p>
            <p>You acknowledge that MUSO.AI is not responsible for any use, disclosure, modification or deletion of User Data that is transmitted to or accessed by a Third Party Product, and that the handling of such User Data within the Third Party Product will be exclusively governed by the separate terms and agreements, if any, between you and such third party provider. You and your users must comply with all terms and conditions applicable to the use of Third Party Products.  You will not use the MUSO.AI Services and API in a manner that damages, disables, overburdens, or impairs any websites, servers, or otherwise interferes with the Third Party Products. You acknowledge that you have sole responsibility for and that you assume all risks arising from your use of any Third Party Products. MUSO.AI does not guarantee the continued availability, operation, or utility of Third Party Products and their use with the MUSO.AI Services. 
            </p>
            <p>(b) <span class="text-italic">Authorizations for Third Party Products.</span> To connect the MUSO.AI Services with Third Party Products, you authorize MUSO.AI to, as applicable: (i) store relevant Account Information; (ii) access the relevant service using the Credentials that you provide; (iii) use and apply any signatures or other materials you provide MUSO.AI in order to provide related services; (iv) gather and export from such Third Party Product any data or other information reasonably necessary to provide related MUSO.AI Services to you; and (v) take action regarding such Third Party Products as is reasonably necessary to provide related services to you.
            </p>
            <p>(c) <span class="text-italic">Management of Third Party Accounts.</span> You are solely responsible for (i) ensuring that any Third Party Product accounts are accurately and properly provisioned for or matched to your MUSO.AI Service account; (ii) ensuring the termination or de-linking of any Third Party Product accounts from your MUSO.AI account (e.g., due to termination of your relationship with such third party); and (iii) otherwise following all instructions provided by MUSO.AI in connection with matching, de-linking, termination or other management of your MUSO.AI accounts in relation to Third Party Products. 
            </p>
            <p>2.6 <span class="text-underline">Prohibited Activities.</span> Any authorization to access or use the MUSO.AI Services extends only to the MUSO.AI Services for which you have subscribed, and for which user conduct is in conformity with these Terms. You will not (nor will you permit any user or third party to):
            </p>
            <ul>
                <li>market or sell your own products or services or those of a third party through use of the MUSO.AI Services; </li>
                <li>reverse engineer, decompile, disassemble or otherwise create, attempt to create or derive the source code underlying the MUSO.AI Services;
                </li>
                <li>transfer, resell, lease, license or assign MUSO.AI Services or otherwise offer the MUSO.AI Services on a standalone basis, or permit any third party to access the MUSO.AI Services (i.e., except for your authorized employees or contractors, if applicable), without express permission from MUSO.AI;
                </li>
                <li>use or access the MUSO.AI Services to build a similar or competitive product or service or for the purpose of obtaining unauthorized access to the MUSO.AI Services;
                </li>
                <li>share your MUSO.AI username and password with any other person, or allow any other person to use your MUSO.AI username and password to access the MUSO.AI Services;
                </li>
                <li>develop, support or use software, devices, scripts, robots or any other means or processes (including crawlers, browser plugins and add-ons or any other technology) to scrape the MUSO.AI Services or otherwise copy profiles and other data from the MUSO.AI Services in order to enable, use or build a similar or competitive product or service;
                </li>
                <li>tamper with the security of MUSO.AI’s systems or tamper with any other accounts of MUSO.AI;
                </li>
                <li>attempt to probe, scan or test the vulnerability of any MUSO.AI systems or to breach the security or authentication measures of MUSO.AI’s systems;
                </li>
                <li>use or launch any automated system, including "robots," "spiders" or "offline readers" that send more requests to our servers in a given period of time than a human can reasonably produce in the same period by using a conventional browser;
                </li>
                <li>use the MUSO.AI Services in any manner that damages, disables, overburdens, or impairs any of our websites, servers or otherwise interferes with any other party's use of the MUSO.AI Services;
                </li>
                <li>access the MUSO.AI Services other than through our website or interface;
                </li>
                <li>engage in harassing or other inappropriate behavior with respect to any MUSO.AI employee;
                </li>
                <li>use the MUSO.AI Services for any fraudulent activity or purpose; or
                </li>
                <li>use the MUSO.AI Services in violation of any applicable law, for illegal activities, or for activities outside the scope expressly permitted hereunder.
                </li>
            </ul>
            <p>For the avoidance of doubt, MUSO.AI welcomes and encourages the responsible disclosure of security vulnerabilities at <a href="mailto:notices@muso.ai">notices@MUSO.AI</a>.
            </p>
            <p>2.7 <span class="text-underline">Compliance with Laws; Digital Millennium Copyright Act</span>.
            (a) <span class="text-italic">Compliance with Laws.</span> You will be solely responsible for compliance with any and all applicable laws, rules and regulations affecting your use of the MUSO.AI Services.   You are also responsible for ensuring that your employees and contractors comply with applicable laws while using the MUSO.AI Services including the intellectual property and third-party rights of others.
            </p>
            <p>(b) <span class="text-italic">Digital Millennium Copyright Act. </span> If you believe that your work has been copied and improperly used as part of the MUSO.AI Services in violation of the Digital Millennium Copyright Act (<span class="text-bold">“DMCA”</span>), you should notify us at <a href="mailto:notices@muso.ai">notices@MUSO.AI</a> of your infringement claim, which shall include: (a) the subject line of <span class="text-bold">“DMCA Takedown Request”</span>; (b) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest (i.e., the person or entity alleging misuse); (c) a description of the copyrighted work or other intellectual property that you claim has been infringed; (d) a description of where the infringing material is located on the MUSO.AI Service, with enough detail that we may find it; (e) your address, telephone number and email address; (f) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent or the law; and (g) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright or intellectual property owner or are otherwise authorized to act on the copyright or intellectual property owner’s behalf. In accordance with the DMCA and other applicable law, MUSO.AI has adopted a policy of terminating users who are deemed to be repeat infringers. MUSO.AI may also limit access to the MUSO.AI Service and/or terminate the memberships of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.
            </p>
            <p>2.8 <span class="text-underline">Trademarks</span>. The names and logos of MUSO.AI and any third parties belong to their respective owners and are used herein with permission. You and your users may not use the name or logo of MUSO.AI or third parties without our or their written consent, as applicable.  Such names and logos are protected by common law, state and/or Federal trademark laws. 
            </p>
            <p class="text-bold">3. Term and Termination.</p>
            <p>3.1 <span class="text-underline">Term.</span> These Terms will commence on the date that you create your account with MUSO.AI and affirm your consent hereto, or if earlier, the date that you begin using any MUSO.AI Service, and will continue until terminated as provided herein (the <span class="text-bold">“Term”</span>). With respect to any MUSO.AI Services provided to you, the subscription term will continue until you or MUSO.AI terminate your subscription (each, a <span class="text-bold">“Subscription Term”</span>). The Subscription Term is simply the period for which you pay fees to use the MUSO.AI Services, and is subsumed within the phrase Term as defined herein.  The Term is month-to-month unless otherwise agreed.</p>
            <p>You may terminate your subscription or any user on thirty (30) days’ written notice to MUSO.AI at <a href="mailto:notices@muso.ai">notices@MUSO.AI</a>.  Because each subscription is prepaid monthly in advance, you will NOT be entitled to a refund in the event of termination of the MUSO.AI Services. </p>
            <p>MUSO.AI may change the MUSO.AI Services, stop providing the MUSO.AI Services or features of it or create usage limits for the MUSO.AI Services for our users generally; provided, that, we will notify you of any material change at least thirty (30) days prior to their implementation, unless the changes are being made for legal reasons, in which case MUSO.AI will notify you within a reasonable time period. If MUSO.AI discontinues a MUSO.AI Service in its entirety, you will not be obligated to pay for the discontinued service after the date that it ceases.</p>
            <p>3.2 <span class="text-underline">Termination by MUSO.AI</span>. MUSO.AI may permanently terminate your access to the MUSO.AI Services without liability to you on thirty (30) days’ prior notice for any actual or suspected violation of these Terms. Separately, you may deactivate your MUSO.AI Services account at any time by using the tools provided in the MUSO.AI Service; provided, however, that (i) such action will not be deemed a termination of the Agreement or any associated payment obligations, as deactivation and termination are different; (ii) these Terms shall continue to apply with regards to protection of MUSO.AI’s intellectual property rights; and (iii) you will remain obligated to pay any outstanding fees to MUSO.AI pursuant to the terms of Section 4.1. Upon termination, the provisions hereof that by their nature extend beyond termination shall continue to apply.  Therefore, if you intend to terminate these Terms and your Subscription, please notify us at <a href="mailto:notices@muso.ai">notices@MUSO.AI</a>. 
            </p>
            <p>3.3 <span class="text-underline">Suspension.</span> Without limiting our other rights or remedies, MUSO.AI may temporarily suspend your access to any portion of the MUSO.AI Services without prior notice if (a) MUSO.AI reasonably determines that (i) there is a threat or attack on the MUSO.AI Services or other event that may create a risk to the MUSO.AI Services, you or any other user; (ii) your use of the MUSO.AI Services disrupts or poses a security risk; or (iii) you are in breach of Section 2.6 (Prohibited Activities) or Section 2.7 (Compliance with Laws; DMCA); or (b) MUSO.AI has notified you that any amount owed by you under these Terms is thirty (30) or more days overdue, and you have failed to submit payment in full within five (5) days of receipt of such notice (collectively, <span class="text-bold">“Service Suspensions”</span>). MUSO.AI will provide notice of any Service Suspension and provide updates regarding resumption of MUSO.AI Services. MUSO.AI will have no liability for any damage, liabilities, losses (including any loss of data or profits) or any other consequences that you may incur as a result of any Service Suspension.
            </p>
            <p class="text-bold">4. Service Fees and Charges.</p>
            <p>4.1 <span class="text-underline">Fees.</span> You agree to pay the fees for the MUSO.AI Services specified in your account, and you may authorize MUSO.AI to conduct automatic debits from your bank account or credits to your credit card for fees as they become payable. Subscription fees are payable at the start of your Subscription and monthly thereafter, and MUSO.AI may, if you elect, debit or credit fees and any charges from your bank account or your credit card company.  Additional user fees are based on the calendar month in which a user is enrolled or added to any MUSO.AI Service, regardless of whether the user is enrolled for only a portion of such month. Notwithstanding the foregoing, MUSO.AI invoices are payable within fifteen (15) days of receipt. Interest shall accrue on past due amounts at the rate of one and one-half percent (1.5%) per month, but in no event greater than the highest rate of interest allowed by law.</p>
            <p>4.2 <span class="text-underline">Automatic Debits and Credits.</span> You may authorize MUSO.AI to automatically debit or credit applicable charges from your designated payment account on the date they become due. Such authorization will remain in effect until termination of this Agreement or you change your user settings. Because these are electronic transactions, funds may be withdrawn from your bank account or charged to your credit card immediately. MUSO.AI may impose a fee of $25 for each transaction returned for insufficient funds, as permitted by applicable law. You certify that you are an authorized user of your bank account and credit card, and that you will not dispute these transactions with your bank. You shall follow rules promulgated by the National Automated Clearing House Association (NACHA), which govern ACH transactions.
            </p>
            <p>4.3 <span class="text-underline">Fee Disputes.</span> You must notify MUSO.AI in writing if you dispute any fees. You must provide written notice to MUSO.AI within ten (10) days of the applicable charge. If you do not provide such notice, you waive any rights to dispute the charges.</p>
            <p>4.4 <span class="text-underline">Taxes.</span> All amounts and fees stated or referred to in these Terms are exclusive of taxes, duties, levies, tariffs, and other governmental charges (collectively, “Taxes”). You shall be responsible for payment of all Taxes and any related interest and/or penalties resulting from any payments made hereunder, other than any taxes based on MUSO.AI’s net income.
            </p>
            <p class="text-bold">5. Proprietary Rights and Confidentiality.</p>
            <p>5.1 <span class="text-underline">MUSO.AI’s Ownership Rights.</span> As between you, your users and MUSO.AI, respectively, all right, title, and interest in and to the MUSO.AI Services, including the MUSO.AI Content, shall remain vested in MUSO.AI. Except for the express rights granted hereunder, MUSO.AI reserves all right, title and interest in the MUSO.AI Services and MUSO.AI’s Confidential Information (as defined below).
            </p>
            <p>5.2 <span class="text-underline">Feedback.</span> You or your users may from time to time provide MUSO.AI with suggestions or comments for enhancements or improvements, new features or functionality regarding the MUSI.AI Services (<span class="text-bold">“Feedback”</span>). MUSO.AI will have full discretion to determine whether or not to proceed with the development of any requested enhancements, new features or functionality. MUSO.AI will have the full, unencumbered right to use, incorporate and otherwise fully exercise and exploit any such Feedback in connection with its products and services.
            </p>
            <p>5.3 <span class="text-underline">User Data.</span> All right, title, and interest in and to the User Data will remain vested in you. Upon termination, MUSO.AI will delete any User Data unless otherwise prohibited by law.
            </p>
            <p>5.4 <span class="text-underline">Confidentiality.</span> <span class="text-bold">“Confidential Information”</span> as used herein means any information or data disclosed by either party that should be reasonably understood to be confidential in light of the nature of the information. For purposes of clarity, Confidential Information need not be marked as such to be confidential for purposes of these Terms.  As to MUSO.AI, its Confidential Information includes, without limitation, its technology, service offerings, pricing, API, and details regarding its user experience, among other things. However, “Confidential Information” will not include any information which (a) is in the public domain through no fault of receiving party; (b) was properly known to receiving party, without restriction, prior to disclosure by the disclosing party; (c) was properly disclosed to receiving party, without restriction, by another person with the legal authority to do so; or (d) is independently developed by the receiving party without use of or reference to the disclosing party’s Confidential Information. Each party will protect any Confidential Information of the other which it may receive or otherwise be exposed to in the course of exercising its rights or performing its obligations hereunder. Each party will use the same care to protect the other’s Confidential Information as it would use to protect its own similar information, but in no event less than reasonable care. Each party will use Confidential Information only for the purpose of fulfilling its obligations or exercising its rights under these Terms, and as otherwise set forth in MUSO.AI’s Privacy Policy (a separate policy that is posted at www.MUSO.AI). Neither party will disclose any Confidential Information of the other to any third party without the prior written consent of the owner; provided, however, that an owner may furnish Confidential Information of the other (e) to its employees and consultants who are required to have access to the Confidential Information in connection with the exercise of receiving party’s rights or performance of its obligations under these Terms; (f) to its professional advisers (e.g., lawyers and accountants); and (g) as otherwise set forth in MUSO.AI’s Privacy Policy; provided, however, that any and all such employees, consultants and advisers are bound by agreements or, in the case of professional advisers, ethical duties, to treat, hold and maintain such Confidential Information in a manner that is consistent with the terms and conditions of this Section.</p>
            <p>5.5 <span class="text-underline">Data Security and Data Processing; Privacy.</span></p>
            <p>(a) <span class="text-italic">Data Security.</span> MUSO.AI will implement and maintain commercially reasonable and industry standard administrative, physical, organizational and technical safeguards to prevent unauthorized use, access, processing, destruction, loss, alteration or disclosure of any User Data. Such safeguards will include, at minimum, an industry standard information security program and procedures to help ensure that only those with a “need to know” have access to such User Data. MUSO.AI will promptly notify you upon becoming aware of an incident that has compromised or may compromise the security, confidentiality or integrity of such User Data. MUSO.AI will comply with all notification obligations that may be required by applicable state and federal laws and regulations. MUSO.AI further reserves the right to protect its network and services from external threats including by restricting network access from various hosting providers, traffic proxies, and locations where MUSO.AI does not conduct business.
            </p>
            <p class="text-bold">6.   Disclaimer.</p>
            <p>THE MUSO.AI SERVICES ARE PROVIDED “AS IS” TO THE FULLEST EXTENT PERMITTED BY LAW. MUSO.AI HEREBY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE REGARDING THE MUSO.AI SERVICES. 

            WITHOUT LIMITING THE FOREGOING, MUSO.AI DOES NOT WARRANT THAT THE MUSO.AI SERVICES WILL BE ERROR-FREE OR THAT THEY WILL MEET ANY SPECIFIED SERVICE LEVEL OR OPERATE WITHOUT INTERRUPTIONS OR DOWNTIME. 

            MUSO.AI DOES NOT WARRANT THE ACCURACY OF ANY INFORMATION CONTAINED IN THE MUSO.AI CONTENT OBTAINED FROM THIRD PARTIES. MUSO.AI DOES NOT VALIDATE CONTENT PROVIDED BY THIRD PARTIES. 

            NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM MUSO.AI OR THE MUSO.AI SERVICES CREATES ANY WARRANTY. MUSO.AI DOES NOT WARRANT, ENDORSE, GUARANTEE OR ASSUME RESPONSIBILITY FOR ANY THIRD PARTY PRODUCTS OR CONTENT. TO THE EXTENT THAT THIS DISCLAIMER CONFLICTS WITH APPLICABLE LAW, THE SCOPE AND DURATION OF ANY APPLICABLE WARRANTY WILL BE THE MINIMUM PERMITTED UNDER THAT LAW.
            </p>
            <p class="text-bold">7. Indemnification.</p>
            <p>7.1 <span class="text-underline">Indemnification by You.</span> You agree to indemnify, defend and hold harmless MUSO.AI against any claim, demand, suit or proceeding (<span class="text-bold">“Claim”</span>) arising out of (a) your unauthorized use of or access to the MUSO.AI Services; (b) your violation of these Terms; (c) your violation of any third-party rights, including any right of privacy or any intellectual property right; (d) your violation of any applicable law, rule or regulation; (e) your use of User Data in a manner that violates these Terms or applicable law; and (f) access to and use of the MUSO.AI Services by unauthorized persons with your or your users’ Credentials. To receive the benefit of this indemnity, MUSO.AI will give you prompt written notice of the Claim and all reasonable cooperation, at your expense, in your defense and settlement of the Claim.
            </p>
            <p>7.2 <span class="text-underline">Indemnification by MUSO.AI.</span> MUSO.AI agrees to indemnify, defend and hold you harmless against any Claim arising out of allegations by a third party that the MUSO.AI Services or any portion thereof infringe(s) or otherwise violate(s) such third party’s U.S. intellectual property rights. To receive the benefit of this indemnity, you must give MUSO.AI prompt written notice of the Claim, sole control to defend and settle it and  reasonable cooperation, at MUSO.AI’s expense, in MUSO.AI’s defense and settlement of the Claim. If a claim under the foregoing clause (a) is made or likely to be made, MUSO.AI may: (i) procure a license to allow you to continue using the allegedly infringing component(s) of the MUSO.AI Services; (ii) modify the infringing component(s) to make them non-infringing; or (b) if (i) and (ii) are not reasonably available, terminate your right to use the infringing component(s) effective immediately.</p>
            <p class="text-bold">8. Limitation of Liability.</p>
            <p>YOU AGREE THAT THE ESSENTIAL PURPOSE OF THIS SECTION 8 IS TO ALLOCATE THE RISKS UNDER THESE TERMS AND TO LIMIT POTENTIAL LIABILITY, GIVEN THAT THE FEES THAT YOU HAVE PAID MUSO.AI WOULD HAVE BEEN SUBSTANTIALLY HIGHER IF MUSO.AI WERE TO ASSUME ANY FURTHER LIABILITY OTHER THAN AS SET-FORTH HEREIN.  MUSO.AI HAS RELIED ON THESE LIMITATIONS IN DETERMINING WHETHER TO PROVIDE YOU WITH ACCESS TO AND USE THE MUSO.AI SERVICES.</p>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, MUSO.AI, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS AND LICENSORS SHALL NOT BE LIABLE FOR (A) ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THESE TERMS, INCLUDING YOUR USE OF OR INABILITY TO USE THE MUSO.AI SERVICES; (B) ERRORS, MISTAKES OR INACCURACIES OF THE MUSO.AI SERVICES; (C) PROPERTY DAMAGE OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF THE MUSO.AI SERVICES; (D) THE CONTENT OF YOUR USER DATA; (E) ANY INTERRUPTION OR CESSATION OF TRANSMISSION OF THE MUSO.AI SERVICES; (F) ANY BUGS, VIRUSES, TROJAN HORSES OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH OUR MUSO.AI SERVICES BY ANY THIRD PARTY; (G) ANY ERRORS OR OMISSIONS IN THE MUSO.AI SERVICES OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED OR OTHERWISE MADE AVAILABLE THROUGH THE MUSO.AI SERVICES; AND/OR (H) THE DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF ANY THIRD PARTY. MUSO.AI, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS AND LICENSORS SHALL NOT BE LIABLE TO YOU FOR DIRECT DAMAGES, IN THE AGGREGATE, EXCEEDING THE AMOUNT YOU PAID MUSO.AI HEREUNDER IN THE TWELVE (12) MONTH PERIOD PRECEDING THE CLAIM THAT GAVE RISE TO SUCH LIABILITY. THE LIMITATIONS IN THIS SECTION APPLY TO THE FULLEST EXTENT PERMITTED BY LAW, EVEN IF MUSO.AI HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p>SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THESE TERMS GIVE YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM STATE TO STATE. THE EXCLUSIONS AND LIMITATIONS OF LIABILITY UNDER THESE TERMS WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW. 
            </p>
            <p class="text-bold">9. Miscellaneous.</p>
            <p>9.1 <span class="text-underline">Assignment; Delegation.</span> This Agreement and your account any rights and licenses granted hereunder may not be transferred or assigned by you without the prior written consent of MUSO.AI. Any attempted transfer or assignment in violation hereof shall be null and void. MUSO.AI, in its sole discretion, may use vendors or contractors to help provide the MUSO.AI Services to you, and MUSO.AI may change its use of vendors or contractors without notice to you. MUSO.AI will remain responsible for the acts and omissions of such vendors and/or contractors.
            </p>
            <p>9.2 <span class="text-underline">Governing Law.</span> This Agreement will be governed by the laws of the State of California, exclusive of its rules governing choice of law and conflict of laws. This Agreement will not be governed by the United Nations Convention on Contracts for the International Sale of Goods. Subject to the agreement to arbitrate below, all disputes arising out of the Agreement will be subject to the exclusive jurisdiction and venue of the state and federal courts in Los Angeles County, California, USA, and the parties hereby consent to the personal jurisdiction of these courts.
            </p>
            <p>9.3 <span class="text-underline">Notices.</span> MUSO.AI may provide notifications to you via email notice, text message, written or hard copy notice, or through posting of such notice on the MUSO.AI Services as determined by MUSO.AI in its sole discretion. MUSO.AI reserves the right to determine the form and means of providing notifications to users. MUSO.AI is not responsible for any automatic filtering that you or your network provider may apply to email notifications sent to the email address that you provide. MUSO.AI may, in its sole discretion, modify or update these Terms from time to time, so please review this page periodically. When MUSO.AI materially changes these Terms, MUSO.AI will update the ‘Last Updated’ date at the top of this page and notify you that material changes have been made to these Terms. Any such changes will become effective no earlier than thirty (30) days after they are posted, except that changes that address new functions of the MUSO.AI Services or changes made for legal reasons will be effective immediately. Your continued use of the MUSO.AI Services after any such change becomes effective constitutes your acceptance of these Terms, as updated. Notices to MUSO.AI shall be made to <a href="mailto:notices@muso.ai">notices@MUSO.AI</a>.
            </p>
            <p>9.4 <span class="text-underline">Waiver.</span> No waiver of any rights will be effective unless assented to in writing. Any such waiver will be to the specific provision for which it was given, and will not apply to repeated or continued violations of these Terms. Failure or delay to enforce any provision of these Terms will not be deemed a waiver of future enforcement of that or another provision.
            </p>
            <p>9.5 <span class="text-underline">Relationship.</span> Nothing contained herein will constitute an association, partnership, agency, employment or joint venture between MUSO.AI, you or your users, or be construed to establish such relationship. Neither MUSO.AI nor you or your users will have the authority to obligate or bind the other in any manner, and nothing herein will give rise to any rights to any third parties.
            </p>
            <p>9.6 <span class="text-underline">Unenforceability.</span> If a court of competent jurisdiction determines that a provision of these Terms is invalid, illegal or otherwise unenforceable, such provision will be enforced in accordance with the stated intention of MUSO.AI and you, while the remainder of these Terms will remain in full force and effect.
            </p>
            <p>9.7 <span class="text-underline">Force Majeure.</span> MUSO.AI will not be deemed in breach hereunder for cessation, interruption or delay in the performance of its obligations due to causes beyond its reasonable control including, without limitation, earthquake, flood or natural disaster, act of God, labor controversy, civil disturbance, terrorism, war (whether or not officially declared) or the inability to obtain sufficient supplies, transportation or other commodity or service required to conduct its business, or any change in or the adoption of any law, regulation, judgment or decree.
            </p>
            <p>9.8 <span class="text-underline">Entire Agreement.</span> This Agreement and any supplemental policies or terms that may be adopted comprise the entire agreement between you and MUSO.AI, and supersedes all prior and contemporaneous proposals, statements, sales materials or presentations and agreements. No oral or written information or advice given by MUSO.AI, its agents or employees will create a warranty or increase the scope of the warranties in these Terms.
            </p>
            <p>9.9 <span class="text-underline">Marketing.</span> You agree that MUSO.AI may use your name and logo on its website and in marketing materials, unless you opt out of such usage by sending an email to <a href="mailto:opt-out@muso.ai">opt-out@MUSO.AI</a>.
            </p>
            <p class="text-bold">10. Agreement to Arbitrate and Class Action Waiver</p>
            <p>10.1 <span class="text-underline">First Try Support.</span> If you have issues with the MUSO.AI Services, you must try to resolve them through MUSO.AI Support. If cannot do so within sixty (60) days, you may pursue the dispute resolution procedures detailed below.
            </p>
            <p>10.2 <span class="text-underline">Agreement to Arbitrate.</span> ANY DISPUTE OR CLAIM RELATING TO OR CONCERNING YOUR USE OF OR ACCESS TO THE MUSO.AI SERVICES AND THESE TERMS (INCLUDING MUSO.AI’S PRIVACY POLICY AND ANY ADDITIONAL TERMS), SHALL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION UNDER THE JURISDICTION OF THE AMERICAN ARBITRATION ASSOCIATION (<span class="text-bold">“AAA”</span>), RATHER THAN IN COURT. THIS ARBITRATION AGREEMENT APPLIES TO ALL SUCH CLAIMS UNDER ANY LEGAL THEORY, UNLESS THE CLAIM FITS IN ONE OF THE EXCEPTIONS IDENTIFIED HEREIN.
            </p>
            <p>This Agreement is governed by the Federal Arbitration Act (<span class="text-bold">“FAA”</span>), including its procedural provisions. This means that the FAA governs, among other things, the interpretation and enforcement of these Terms and all of its provisions including, without limitation, the class action waiver discussed below. State arbitration laws do not govern in any respect.
            </p>
            <p>This Agreement is intended to be broadly interpreted and will survive termination, which means (among other things) that these Terms apply even after you have stopped using your MUSO.AI account or have deleted it. The arbitrator and not any federal, state or local court or agency shall have exclusive authority to the extent permitted by law to resolve all disputes arising out of or relating to the interpretation, applicability, enforceability or formation of these Terms including, but not limited to, any claim that all or any part of these Terms is void or voidable. If the parties have a dispute about whether these Terms can be enforced, whether these Terms apply to a dispute, or any other dispute about the meaning or scope of these Terms, the parties agree that the arbitrator shall have exclusive authority to resolve the dispute.
            </p>
            <p>There is no judge or jury in arbitration, and court review of an arbitration award is limited. However, an arbitrator can award, on an individual basis, the same damages and relief as a court (including injunctive and declaratory relief or statutory damages) and must follow these Terms as a court would. For the avoidance of doubt, the arbitrator can award injunctive relief.
            </p>
            <p>If these Terms are, for any reason, held to be unenforceable or inapplicable to a claim, any litigation against MUSO.AI (except for the intellectual property and small claims actions described in Section 10.3 below) may be commenced only in a federal or state court located within Los Angeles County, California, and both parties consent to the jurisdiction of those courts for such purposes.
            </p>
            <p>10.3 <span class="text-underline">Exceptions to Agreement to Arbitrate.</span> You and MUSO.AI agree that our agreement to arbitrate will not apply to any disputes relating to your or MUSO.AI’s intellectual property (e.g., trademarks, trade dress, domain names, trade secrets, copyrights or patents) and that such disputes may be brought in any court that has jurisdiction over such claims. Also, either party can bring a claim in small claims court in Los Angeles, California if the claim qualifies to be brought in that court.
            </p>
            <p>10.4 <span class="text-underline">Details of Arbitration Procedure.</span></p>
            <p>(a) <span class="text-italic">Informal Resolution.</span> You and MUSO.AI agree that good-faith, informal efforts to resolve disputes often can result in a prompt, low-cost and mutually beneficial outcome. Prior to demanding or filing an arbitration, you and MUSO.AI agree to personally meet and confer in person or by videoconference in a good-faith effort to resolve any claim covered by these Terms. If you are represented by counsel, your counsel may participate in the conference, but you shall also fully participate in it. The party initiating the claim must give notice to the other in writing of the intent to initiate an informal dispute resolution conference, which shall occur within 60 days after issuance of such notice, unless an extension is mutually agreed upon. To notify MUSO.AI that you intend to initiate an informal dispute resolution conference, email MUSO.AI at notices@MUSO.AI with the subject “INFORMAL DISPUTE RESOLUTION REQUEST” and provide your name, the telephone number and email address associated with your MUSO.AI account, and a description of your claim. The statute of limitations and any filing fee deadlines shall be tolled while the parties engage in the informal dispute resolution process described in this paragraph.
            </p>
            <p>(b) If the informal dispute resolution process does not result in a resolution, either party may initiate an arbitration proceeding under the commercial arbitration rules of the AAA (the <span class="text-italic">“Rules”</span>). To the extent anything described in these Terms conflicts with the Rules, the language of these Terms applies. Any arbitration will be conducted in Los Angeles County,  California, or in another location that both parties agree to in writing or over Zoom or another such teleconference medium.
            </p>
            <p>(c) <span class="text-italic">Discovery.</span> Each party will be entitled to obtain a copy of non-privileged, relevant documents in the possession or control of the other party, and each party may take two (2) depositions. All such discovery will be in accordance with the procedures approved by the arbitrator. This Agreement does not alter the statute of limitations that apply to any claims or counterclaims asserted by either party.
            </p>
            <p>(d) <span class="text-italic">Arbitration Award.</span> The arbitrator’s award will be based on the evidence admitted and the substantive law of the State of California and the United States, as applicable, and will contain an award for each issue and counterclaim. The award will provide in writing the factual findings and legal reasoning for such award. The arbitrator will not be entitled to modify these Terms, and may not award any relief that is inconsistent with these Terms.
            </p>
            <p>(e) <span class="text-italic">Final and Binding.</span> Except as provided in the FAA, the arbitration award will be final and binding on the parties. Judgment may be entered in any court of competent jurisdiction.
            </p>
            <p>10.5 <span class="text-underline">Class Action Waiver.</span> You and MUSO.AI agree that any claims or controversies between us must be brought on an individual basis only, and not in a class, consolidated, or representative action. That means neither you nor MUSO.AI may bring such a claim as a plaintiff or class member in a class action, consolidated action or representative action. The arbitrator cannot combine or consolidate more than one person’s or entity’s claims into a single case, and cannot preside over any consolidated, class or representative proceeding (unless all parties agree otherwise in writing). Further, the arbitrator’s decision or award in one person’s or entity’s case can only impact the person or entity that brought the claim and not any other persons or entities including MUSO.AI, you or your users, and cannot be used as precedent to decide other disputes with other parties.  YOU AGREE (i) TO WAIVE ANY RIGHT TO A JURY TRIAL; (ii) TO WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS-WIDE OR REPRESENTATIVE ARBITRATION OR LAWSUIT; AND (iii) TO WAIVE ANY RIGHT TO PARTICIPATE IN ANY CLASS ACTION LAWSUIT (INCLUDING FOR ANY CLAIM THAT IS DETERMINED NOT TO BE SUBJECT TO ARBITRATION UNDER THESE TERMS). If a court decides that this class action waiver is not enforceable or valid, then the entire agreement to arbitrate will be null and void, but the rest of these Terms will still apply.
            </p>
            <p>&copy; 2021 MUSO.AI</p>
        </div>
    </div>
</template>

<script>
</script>

<style lang='scss' scoped>
    .terms-container {
        color: #6B6B6B;
        text-align: left;
        background-color: #FFFFFF;
        font-family: "Helvetica Neue";
        
        & .inner-container {
            max-width: 900px;
            margin: auto;
            display: flex;
            flex-wrap: wrap;
            flex-direction: column;
            justify-content: center;
            align-items: self-start;
            padding-top: 30px;
            padding-bottom: 30px;
        }
        & .main-title {
            font-size: 16px;
        }
        & .text-bold {
            font-weight: 900;
        }
        & .text-underline {
            text-decoration: underline;
        }
        & .text-italic {
            font-style: italic;
        }
        & .flex-align {
            &__center {
                align-self: center;
            }
        }
        & p {
            margin-top: 10px;
            & a {
                text-decoration: underline;
            }
        }
    }
</style>